# ===================================================================
# Activate this profile to enable TLS and HTTP/2.
#
# JHipster has generated a self-signed certificate, which will be used to encrypt traffic.
# As your browser will not understand this certificate, you will need to import it.
#
# Another (easiest) solution with Chrome is to enable the "allow-insecure-localhost" flag
# at chrome://flags/#allow-insecure-localhost
# ===================================================================
server:
    ssl:
        key-store: classpath:config/tls/aisa.p12
        key-store-password: aisaK3y4dm1n5t0r3
        key-store-type: PKCS12
        key-alias: aisa
jhipster:
    http:
        version: V_2_0
